# Generated by Django 5.1.6 on 2025-04-24 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_response_agent_alter_supportcase_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcase',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
